version: "3.1"
services:
  grafana:
    image: grafana/grafana:11.1.6-ubuntu
    ports:
      - "3000:3000"
    networks:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - "9090:9090"
    networks:
      - loki
    volumes:
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
      - ./alertmanager/alert.rules.yml:/alertmanager/alert.rules.yml
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter:v1.8.1
    ports:
      - "9100:9100"
    networks:
      - loki
    volumes:
      - prom-data:/prometheus
      - ./alertmanager/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.external-url=http://127.0.0.1:9090"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    ports:
      - "8081:8080"
    networks:
      - loki
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    networks:
      - loki
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
networks:
  loki:
    driver: overlay
    attachable: true
volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
